# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rev2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(442, 467)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.startup_tab = QtWidgets.QWidget()
        self.startup_tab.setObjectName("startup_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.startup_tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.push_connect = QtWidgets.QPushButton(self.startup_tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.push_connect.setFont(font)
        self.push_connect.setObjectName("push_connect")
        self.verticalLayout.addWidget(self.push_connect)
        self.push_home = QtWidgets.QPushButton(self.startup_tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.push_home.setFont(font)
        self.push_home.setObjectName("push_home")
        self.verticalLayout.addWidget(self.push_home)
        self.push_zeros = QtWidgets.QPushButton(self.startup_tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.push_zeros.setFont(font)
        self.push_zeros.setObjectName("push_zeros")
        self.verticalLayout.addWidget(self.push_zeros)
        self.push_calibrate = QtWidgets.QPushButton(self.startup_tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.push_calibrate.setFont(font)
        self.push_calibrate.setObjectName("push_calibrate")
        self.verticalLayout.addWidget(self.push_calibrate)
        self.push_reset = QtWidgets.QPushButton(self.startup_tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.push_reset.setFont(font)
        self.push_reset.setObjectName("push_reset")
        self.verticalLayout.addWidget(self.push_reset)
        self.push_disconnect = QtWidgets.QPushButton(self.startup_tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.push_disconnect.setFont(font)
        self.push_disconnect.setObjectName("push_disconnect")
        self.verticalLayout.addWidget(self.push_disconnect)
        self.tabWidget.addTab(self.startup_tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.j0_label = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.j0_label.setFont(font)
        self.j0_label.setObjectName("j0_label")
        self.gridLayout_2.addWidget(self.j0_label, 0, 0, 1, 1)
        self.j0_abs_line_edit = QtWidgets.QLineEdit(self.tab_2)
        self.j0_abs_line_edit.setObjectName("j0_abs_line_edit")
        self.gridLayout_2.addWidget(self.j0_abs_line_edit, 0, 1, 1, 1)
        self.j0_absolute_push = QtWidgets.QPushButton(self.tab_2)
        self.j0_absolute_push.setObjectName("j0_absolute_push")
        self.gridLayout_2.addWidget(self.j0_absolute_push, 0, 2, 1, 1)
        self.j0_rel_line_edit = QtWidgets.QLineEdit(self.tab_2)
        self.j0_rel_line_edit.setObjectName("j0_rel_line_edit")
        self.gridLayout_2.addWidget(self.j0_rel_line_edit, 1, 1, 1, 1)
        self.j0_relative_push = QtWidgets.QPushButton(self.tab_2)
        self.j0_relative_push.setObjectName("j0_relative_push")
        self.gridLayout_2.addWidget(self.j0_relative_push, 1, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.tab_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 2, 0, 1, 3)
        self.j1_label = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.j1_label.setFont(font)
        self.j1_label.setObjectName("j1_label")
        self.gridLayout_2.addWidget(self.j1_label, 3, 0, 1, 1)
        self.j1_abs_line_edit = QtWidgets.QLineEdit(self.tab_2)
        self.j1_abs_line_edit.setObjectName("j1_abs_line_edit")
        self.gridLayout_2.addWidget(self.j1_abs_line_edit, 3, 1, 1, 1)
        self.j1_absolute_push = QtWidgets.QPushButton(self.tab_2)
        self.j1_absolute_push.setObjectName("j1_absolute_push")
        self.gridLayout_2.addWidget(self.j1_absolute_push, 3, 2, 1, 1)
        self.j1_rel_line_edit = QtWidgets.QLineEdit(self.tab_2)
        self.j1_rel_line_edit.setObjectName("j1_rel_line_edit")
        self.gridLayout_2.addWidget(self.j1_rel_line_edit, 4, 1, 1, 1)
        self.j1_relative_push = QtWidgets.QPushButton(self.tab_2)
        self.j1_relative_push.setObjectName("j1_relative_push")
        self.gridLayout_2.addWidget(self.j1_relative_push, 4, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.tab_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 5, 0, 1, 3)
        self.j2_label = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.j2_label.setFont(font)
        self.j2_label.setObjectName("j2_label")
        self.gridLayout_2.addWidget(self.j2_label, 6, 0, 1, 1)
        self.j2_abs_line_edit = QtWidgets.QLineEdit(self.tab_2)
        self.j2_abs_line_edit.setObjectName("j2_abs_line_edit")
        self.gridLayout_2.addWidget(self.j2_abs_line_edit, 6, 1, 1, 1)
        self.j2_absolute_push = QtWidgets.QPushButton(self.tab_2)
        self.j2_absolute_push.setObjectName("j2_absolute_push")
        self.gridLayout_2.addWidget(self.j2_absolute_push, 6, 2, 1, 1)
        self.j2_rel_line_edit = QtWidgets.QLineEdit(self.tab_2)
        self.j2_rel_line_edit.setObjectName("j2_rel_line_edit")
        self.gridLayout_2.addWidget(self.j2_rel_line_edit, 7, 1, 1, 1)
        self.j2_relative_push = QtWidgets.QPushButton(self.tab_2)
        self.j2_relative_push.setObjectName("j2_relative_push")
        self.gridLayout_2.addWidget(self.j2_relative_push, 7, 2, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.tab_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 8, 0, 1, 3)
        self.j3_label = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.j3_label.setFont(font)
        self.j3_label.setObjectName("j3_label")
        self.gridLayout_2.addWidget(self.j3_label, 9, 0, 1, 1)
        self.j3_abs_line_edit = QtWidgets.QLineEdit(self.tab_2)
        self.j3_abs_line_edit.setObjectName("j3_abs_line_edit")
        self.gridLayout_2.addWidget(self.j3_abs_line_edit, 9, 1, 1, 1)
        self.j3_absolute_push = QtWidgets.QPushButton(self.tab_2)
        self.j3_absolute_push.setObjectName("j3_absolute_push")
        self.gridLayout_2.addWidget(self.j3_absolute_push, 9, 2, 1, 1)
        self.j3_rel_line_edit = QtWidgets.QLineEdit(self.tab_2)
        self.j3_rel_line_edit.setObjectName("j3_rel_line_edit")
        self.gridLayout_2.addWidget(self.j3_rel_line_edit, 10, 1, 1, 1)
        self.j3_relative_push = QtWidgets.QPushButton(self.tab_2)
        self.j3_relative_push.setObjectName("j3_relative_push")
        self.gridLayout_2.addWidget(self.j3_relative_push, 10, 2, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.tab_2)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_2.addWidget(self.line_4, 11, 0, 1, 3)
        self.j4_label = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.j4_label.setFont(font)
        self.j4_label.setObjectName("j4_label")
        self.gridLayout_2.addWidget(self.j4_label, 12, 0, 1, 1)
        self.j4_abs_line_edit = QtWidgets.QLineEdit(self.tab_2)
        self.j4_abs_line_edit.setObjectName("j4_abs_line_edit")
        self.gridLayout_2.addWidget(self.j4_abs_line_edit, 12, 1, 1, 1)
        self.j4_absolute_push = QtWidgets.QPushButton(self.tab_2)
        self.j4_absolute_push.setObjectName("j4_absolute_push")
        self.gridLayout_2.addWidget(self.j4_absolute_push, 12, 2, 1, 1)
        self.j4_rel_line_edit = QtWidgets.QLineEdit(self.tab_2)
        self.j4_rel_line_edit.setObjectName("j4_rel_line_edit")
        self.gridLayout_2.addWidget(self.j4_rel_line_edit, 13, 1, 1, 1)
        self.j4_relative_push = QtWidgets.QPushButton(self.tab_2)
        self.j4_relative_push.setObjectName("j4_relative_push")
        self.gridLayout_2.addWidget(self.j4_relative_push, 13, 2, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 14, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 442, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.push_connect.setText(_translate("MainWindow", "Connect"))
        self.push_home.setText(_translate("MainWindow", "Home All Joints"))
        self.push_zeros.setText(_translate("MainWindow", "\"Zeros\" Position"))
        self.push_calibrate.setText(_translate("MainWindow", "Calibrate All Joints"))
        self.push_reset.setText(_translate("MainWindow", "\"Reset\" Position"))
        self.push_disconnect.setText(_translate("MainWindow", "Disconnect"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.startup_tab), _translate("MainWindow", "Startup"))
        self.j0_label.setText(_translate("MainWindow", "Joint 0"))
        self.j0_absolute_push.setText(_translate("MainWindow", "Move Absolute"))
        self.j0_relative_push.setText(_translate("MainWindow", "Move Relative"))
        self.j1_label.setText(_translate("MainWindow", "Joint 1"))
        self.j1_absolute_push.setText(_translate("MainWindow", "Move Absolute"))
        self.j1_relative_push.setText(_translate("MainWindow", "Move Relative"))
        self.j2_label.setText(_translate("MainWindow", "Joint 2"))
        self.j2_absolute_push.setText(_translate("MainWindow", "Move Absolute"))
        self.j2_relative_push.setText(_translate("MainWindow", "Move Relative"))
        self.j3_label.setText(_translate("MainWindow", "Joint 3"))
        self.j3_absolute_push.setText(_translate("MainWindow", "Move Absolute"))
        self.j3_relative_push.setText(_translate("MainWindow", "Move Relative"))
        self.j4_label.setText(_translate("MainWindow", "Joint 4"))
        self.j4_absolute_push.setText(_translate("MainWindow", "Move Absolute"))
        self.j4_relative_push.setText(_translate("MainWindow", "Move Relative"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Joint Motion"))

